version: '3.6'
services:
  competitions:
    build: .
    ports:
      - "8080:8080"
    links:
      - "mongodb"
    depends_on:
      - mongodb
  mongodb:
    image: mongo

#    ports:
#      - 27017:27017